### ISSUE TITLE
I can't import MultiHeadAttention

### ISSUE THREAD

**Issue by q865516854** [FernandoJRS/violence-detection-deeplearning#1]
Hi,my TensorFlow version < 2.5, so I can't import MultiHeadAttention,
Is there any other way to use MultiHeadAttention？

**Comment by FernandoJRS** [comment]
Hello.

Multi-Head Self-Attention is not in all versions of TensorFlow but there are versions <2.5 that allow using these layers like version 2.4.  Another way is to install the Keras 'pip install keras'.

https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/keras/layers/MultiHeadAttention
