### ISSUE TITLE
Error in the last cell (dimension must be integer...) 

### ISSUE THREAD

**Issue by TinhinaneMEZAIR** [FernandoJRS/violence-detection-deeplearning#2]
Hello,
There is a bug in the last part of the code that prevents me from running it, here is the error (attached screenshot)
Kind regards
![image](https://user-images.githubusercontent.com/76223314/131671232-c069d817-500b-4a96-927c-f62cf66d24f5.png)
Edit: I found the error, it is in :
net59 = tf.keras.layers.MultiHeadAttention(num_heads=6, key_dim=(32/6), attention_axes=(1, 2, 3))(net59, net59, net59, None)
instead of 32/6=5.333 it should be an int. Please in your model, this int is 6 or 5?

**Comment by FernandoJRS** [comment]
Right, thanks for the note, I must have transcribed wrong when I uploaded the code. I have corrected it and the model compiles correctly.

Kind regards.

![2021-09-02](https://user-images.githubusercontent.com/12451479/131753773-ad13c0b6-31e0-4810-899a-8559940c5127.png)
